# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import model_pb2 as model__pb2


class FederatedLearningStub(object):
    """定义服务接口
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadModelParams = channel.unary_unary(
                '/federated_learning.FederatedLearning/UploadModelParams',
                request_serializer=model__pb2.ModelParams.SerializeToString,
                response_deserializer=model__pb2.ServerResponse.FromString,
                )


class FederatedLearningServicer(object):
    """定义服务接口
    """

    def UploadModelParams(self, request, context):
        """客户端上传模型参数
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedLearningServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadModelParams': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadModelParams,
                    request_deserializer=model__pb2.ModelParams.FromString,
                    response_serializer=model__pb2.ServerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'federated_learning.FederatedLearning', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FederatedLearning(object):
    """定义服务接口
    """

    @staticmethod
    def UploadModelParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/federated_learning.FederatedLearning/UploadModelParams',
            model__pb2.ModelParams.SerializeToString,
            model__pb2.ServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
