name: myenv  # Conda 环境的名称
channels:
  - defaults  # 默认的 Conda 渠道
  - conda-forge  # Conda 的社区源，提供更多包
dependencies:
  - python=3.9  # 创建 Python 3.9 环境
  - pip  # 包含 pip 用于安装额外的 Python 包
  - pip:
      - flwr==1.8.0
      - grpcio==1.62.1
      - grpcio-tools==1.62.1
      - protobuf==4.25.3
      - paho-mqtt==1.6.1
      - tensorflow==2.13.0
      - numpy==1.23.5
  #- cudatoolkit=11.8  # 如果你有支持的 NVIDIA GPU，可以启用 CUDA 支持
