/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_MODEL_PB_H_INCLUDED
#define PB_MODEL_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _ParamType {
    ParamType_UNKNOWN = 0,
    ParamType_ENCODER_WEIGHT = 1,
    ParamType_ENCODER_BIAS = 2,
    ParamType_CLASSIFIER_WEIGHT = 3,
    ParamType_CLASSIFIER_BIAS = 4,
    ParamType_FULL_MODEL = 5
} ParamType;

/* Struct definitions */
typedef struct _ModelParams {
    ParamType param_type;
    pb_callback_t values;
    int32_t client_id;
} ModelParams;

typedef struct _ServerResponse {
    pb_callback_t message;
    bool update_successful;
    int64_t update_timestamp;
} ServerResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _ParamType_MIN ParamType_UNKNOWN
#define _ParamType_MAX ParamType_FULL_MODEL
#define _ParamType_ARRAYSIZE ((ParamType)(ParamType_FULL_MODEL+1))

#define ModelParams_param_type_ENUMTYPE ParamType



/* Initializer values for message structs */
#define ModelParams_init_default                 {_ParamType_MIN, {{NULL}, NULL}, 0}
#define ServerResponse_init_default              {{{NULL}, NULL}, 0, 0}
#define ModelParams_init_zero                    {_ParamType_MIN, {{NULL}, NULL}, 0}
#define ServerResponse_init_zero                 {{{NULL}, NULL}, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ModelParams_param_type_tag               1
#define ModelParams_values_tag                   2
#define ModelParams_client_id_tag                3
#define ServerResponse_message_tag               1
#define ServerResponse_update_successful_tag     2
#define ServerResponse_update_timestamp_tag      3

/* Struct field encoding specification for nanopb */
#define ModelParams_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    param_type,        1) \
X(a, CALLBACK, REPEATED, FLOAT,    values,            2) \
X(a, STATIC,   SINGULAR, INT32,    client_id,         3)
#define ModelParams_CALLBACK pb_default_field_callback
#define ModelParams_DEFAULT NULL

#define ServerResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   message,           1) \
X(a, STATIC,   SINGULAR, BOOL,     update_successful,   2) \
X(a, STATIC,   SINGULAR, INT64,    update_timestamp,   3)
#define ServerResponse_CALLBACK pb_default_field_callback
#define ServerResponse_DEFAULT NULL

extern const pb_msgdesc_t ModelParams_msg;
extern const pb_msgdesc_t ServerResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ModelParams_fields &ModelParams_msg
#define ServerResponse_fields &ServerResponse_msg

/* Maximum encoded size of messages (where known) */
/* ModelParams_size depends on runtime parameters */
/* ServerResponse_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
