# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\"P\n\x0bModelParams\x12\x1e\n\nparam_type\x18\x01 \x01(\x0e\x32\n.ParamType\x12\x0e\n\x06values\x18\x02 \x03(\x02\x12\x11\n\tclient_id\x18\x03 \x01(\x05\"V\n\x0eServerResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x19\n\x11update_successful\x18\x02 \x01(\x08\x12\x18\n\x10update_timestamp\x18\x03 \x01(\x03*z\n\tParamType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x12\n\x0e\x45NCODER_WEIGHT\x10\x01\x12\x10\n\x0c\x45NCODER_BIAS\x10\x02\x12\x15\n\x11\x43LASSIFIER_WEIGHT\x10\x03\x12\x13\n\x0f\x43LASSIFIER_BIAS\x10\x04\x12\x0e\n\nFULL_MODEL\x10\x05\x32y\n\x11\x46\x65\x64\x65ratedLearning\x12\x32\n\x11UploadModelParams\x12\x0c.ModelParams\x1a\x0f.ServerResponse\x12\x30\n\x0fGetUpdateStatus\x12\x0c.ModelParams\x1a\x0f.ServerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PARAMTYPE']._serialized_start=185
  _globals['_PARAMTYPE']._serialized_end=307
  _globals['_MODELPARAMS']._serialized_start=15
  _globals['_MODELPARAMS']._serialized_end=95
  _globals['_SERVERRESPONSE']._serialized_start=97
  _globals['_SERVERRESPONSE']._serialized_end=183
  _globals['_FEDERATEDLEARNING']._serialized_start=309
  _globals['_FEDERATEDLEARNING']._serialized_end=430
# @@protoc_insertion_point(module_scope)
